permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: yyxs
  email: 982273010@qq.com
  link: https://github.com/yyxs
  weibo: http://weibo.com/yyxs
  github: https://github.com/yyxs

# 站点信息
title: yyxs's blog
description: yyxs's博客
url: http://yyxs.github.io
rss_url: /pages/atom.xml

#多说配置
duoshuo_short_name: xsyy

#Google站内搜索
google_cx: google

# avatar头像及Favicon
avatar: http://tp3.sinaimg.cn/3148668390/180/5740316999/1
favicon: http://tp3.sinaimg.cn/3148668390/180/5740316999/1
